<div id="index-wrapper">
	<article class="index-article">
		<header>
			<hgroup>
				<h1>Whiteboard</h1>
				<h2>Canvas drawing application</h2>
			</hgroup>
		</header>
		<section>
			<p>An old assignment from my computer studies days.</p>
			<p>I as looking into some project to do that could force me into reading about
				the &lt;canvas&gt; element. When I was it school I has to do a in-browser-drawing-application. 
				At the time I implemented it in &lt;svg&gt; but I thought that I could rewrite it using
				&lt;canvas&gt;</p>
			<p>My criteria or rules that I layed out were that the code had to be modular end easally 
				extendable in the <a href="http://en.wikipedia.org/wiki/Open/closed_principle" target="_blank">Open/closed 
				principle</a>, I could not use any third-party library but I could use any cutting edge JavaScript that
				was available in what ever browser. (This excluted Internet Explorer).
			</p>
		</section>
		<footer>
			<ul>
				<li><a href="/whiteboard">application</a></li>
				<li><a href="/whiteboard/about">about</a></li>
			</ul>
		</footer>
	</article>

	<article class="index-article">
		<header>
			<hgroup>
				<h1>Alþingi</h1>
				<h2>I got the stream</h2>
			</hgroup>
		</header>
		<section>
			<p>Blabla jólakaka</p>	
		</section>
		<footer>
			<ul>
				<li><a href="/althingi/member">application</a></li>
				<li><a href="/althingi/about">about</a></li>
			</ul>
		</footer>
	</article>
</div>