<?php
	
	$this->headLink(array(
		"rel" => "stylesheet/less",
		"type" => "text/css",
		"href" => "/modules/application/styles/app.less"
	));

	$this->headTitle("Index");
	
?>


<div class="page-wrapper">

	<article id="profile-article" class="index-article">
		<header>
			<hgroup>
				<h1>Me, me, me</h1>
				<h2>A litlebit about me</h2>
			</hgroup>
		</header>
		<section>
			<p>
				<img src="/images/profile-image.jpg">
				A programmer, graphic designer/artist, instrument player and 
				more, this is me. Or it just to be me
			</p>
			<p>Lorem ipsum laborum proident aute magna Ut reprehenderit officia 
				aute pariatur occaecat sint aliquip deserunt ad dolor elit Duis 
				Excepteur commodo labore velit labore in sunt deserunt Duis aute 
				culpa cupidatat. </p>
			<p>Lorem ipsum in do velit irure cupidatat minim ut consequat do est 
				aliqua aute mollit sint culpa minim cillum adipisicing veniam dolore. </p>
		</section>
	</article>

	<article class="">
		<header>
			<hgroup>
				<h1>Whiteboard</h1>
				<h2>Canvas drawing application</h2>
			</hgroup>
		</header>
		<section>
			<p>An old assignment from my computer studies days.</p>
			<p>I as looking into some project to do that could force me into reading about
				the &lt;canvas&gt; element. When I was it school I has to do a in-browser-drawing-application. 
				At the time I implemented it in &lt;svg&gt; but I thought that I could rewrite it using
				&lt;canvas&gt;</p>
			<p>My criteria or rules that I layed out were that the code had to be modular end easally 
				extendable in the <a href="http://en.wikipedia.org/wiki/Open/closed_principle" target="_blank">Open/closed 
				principle</a>, I could not use any third-party library but I could use any cutting edge JavaScript that
				was available in what ever browser. (This excluted Internet Explorer).
			</p>
		</section>
		<footer>
			<ul>
				<li><a href="/whiteboard">application</a></li>
				<li><a href="/whiteboard/about">about</a></li>
			</ul>
		</footer>
	</article>

	<article class="">
		<header>
			<hgroup>
				<h1>Alþingi</h1>
				<h2>I got the stream</h2>
			</hgroup>
		</header>
		<section>
			<p>Lorem ipsum dolor sed sint nisi fugiat proident velit fugiat velit culpa ut aliquip 
				fugiat qui magna tempor esse minim in Duis aliquip in ut sunt ut laborum eiusmod 
				pariatur voluptate exercitation ut pariatur deserunt sit irure ut nulla adipisicing 
				veniam eu dolore do ut nisi consectetur qui ullamco sint voluptate eiusmod velit 
				enim sint elit do cillum et enim culpa tempor proident consequat nulla irure 
				voluptate sed pariatur dolore Excepteur ut commodo est sed aliquip aliquip deserunt 
				aute sunt enim anim in in aute minim tempor occaecat sit in culpa sed reprehenderit 
				in exercitation est exercitation enim do consequat culpa eiusmod irure ex est elit 
				pariatur ex qui deserunt consequat esse aliquip in cillum mollit laboris anim voluptate 
				consequat dolor ullamco eiusmod elit ad officia culpa ad laboris laborum Excepteur 
				labore eiusmod anim sint laborum proident mollit amet reprehenderit occaecat dolor ea 
				nostrud nostrud sed est ullamco occaecat id aliqua irure veniam mollit sint ad cillum 
				non Duis nisi aute est laborum officia elit tempor nisi irure deserunt veniam consectetur 
				enim labore dolore Duis ullamco voluptate Duis sed et dolore nostrud sint tempor aute in 
				adipisicing ut pariatur Ut esse sunt veniam eiusmod ut magna aute nostrud deserunt ex. </p>	
		</section>
		<footer>
			<ul>
				<li><a href="/althingi">application</a></li>
			</ul>
		</footer>
	</article>

	<article class="">
		<header>
			<hgroup>
				<h1>Music</h1>
				<h2>...or how's the best?</h2>
			</hgroup>
		</header>
		<section>
			<p>An old assignment from my computer science studdy days</p>
		</section>
		<footer>
			<ul>
				<li><a href="/music">application</a></li>
				<li><a href="http://tsort.info/music/index.htm" target="_blank">source</a></li>
			</ul>
		</footer>
	</article>

	<article class="">
		<header>
			<h1>SVG</h1>
		</header>
		<section>
			<p>Using SVG images in layout</p>
			<img id="index-logo" src="/styles/images/header-logo.svg" />
		</section>
	</article>

</div>
